services:
  - type: web
    name: lovemenow
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --workers 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: lovemenow-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false  # Set manually in Render dashboard
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false  # Set manually in Render dashboard
      - key: SENDLAYER_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: DOMAIN
        value: https://lovemenow.onrender.com  # Update with your actual domain
    healthCheckPath: /api/health
    
databases:
  - name: lovemenow-db
    databaseName: lovemenow
    user: lovemenow_user